### ISSUE TITLE
Warn if Docker service is not started

### ISSUE THREAD

**Issue by routeback** [audibleblink/doxycannon#19]
If the Docker service is not running when you attempt to use Doxycannon, it will spit out a big python error. Add a catch for this error and instruct the user to start docker.

```
root:$ ./doxycannon.py --build
('Connection aborted.', error(2, 'No such file or directory'))
Traceback (most recent call last):
  File "./doxycannon.py", line 312, in <module>
    main()
  File "./doxycannon.py", line 300, in main
    build(IMAGE)
  File "./doxycannon.py", line 66, in build
    doxy.images.build(path=path, tag=image_name)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/images.py", line 258, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 259, in build
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 194, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

root:$ service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com
root:$ service docker start
root:$ ./doxycannon.py --build
[*] Image audibleblink/doxycannon built.

**Comment by audibleblink** [comment]
good call
